#include <iostream>
#include <exception>

void myunexpected () {
    std::cerr << "unexpected handler called\n";
    throw;
}

void myfunction () throw (int,std::bad_exception) {
    throw std::bad_exception("hello world "); // throws char (not in exception-specification)
    //throw 1;
    //throw "other";
}


int _tmain(int argc, _TCHAR* argv[])
{
    std::set_unexpected (myunexpected);
    try {
        myfunction();
    }
    catch (int) { std::cerr << "caught int\n"; }
    catch (std::bad_exception be) { std::cerr << be.what() << "caught bad_exception\n"; }
    catch (...) { std::cerr << "caught some other exception\n"; }
    system("pause");
}
